### ISSUE TITLE
Let `install_version` install binary packages from MRAN

### ISSUE THREAD

**Issue by wush978** [r-pkgs/remotes#51]
Hi,

Is it possible to let the function `install_version` automatically install the binary packages from [MRAN 's historical snapshots of CRAN](https://mran.microsoft.com/timemachine/)?

**Comment by gaborcsardi** [comment]
I don't see how we could do that. How would you map a version to a date?

**Comment by cderv** [comment]
I do not know if it worth something and I am thinkink out loud.

*DESCRIPTION* file of a package links a version to a date.  It would mean having a service that keeps track of new version and when they occured by parsing this file.

A service like [CRANBERRIES](http://dirk.eddelbuettel.com/cranberries) could be a start as it an example of a database built from calls to `available_packages` and recording each new package each day. The database build for this service could be useful to answer questions like *what is the update history of a package ?* and *When a version was released ?*
Based on this, we could imagine a way to search for a version, find its realeased date and install this version and its dependency from MRAN snapshot.

**Comment by gaborcsardi** [comment]
> DESCRIPTION file of a package links a version to a date. It would mean having a service that keeps track of new version and when they occured by parsing this file.

Yes and no. The `Date` field is optional and it is often not the actual release date. There is also a `Date/Publication` field, at least recently, which is better.

> The database build for this service could be useful to answer questions 

This database already exists: https://github.com/metacran/crandb#readme

> like what is the update history of a package ? 

E.g. http://crandb.r-pkg.org/igraph/all

> and When a version was released ?

E.g. http://crandb.r-pkg.org/igraph/0.2

> Based on this, we could imagine a way to search for a version, find its realeased date and install this version and its dependency from MRAN snapshot.

There are several problems with this approach:
* packages sometimes need to be rebuilt, because of updates for build-time dependencies. I.e. MRAN has actually different files with the same names, over time, sometimes.
* windows binary packages are usually built 1-2 days after the package is on CRAN. So if you take the release date, the package is usually not there yet.
* windows binary packages only exists for 1-2 R versions and they are incompatible with other R versions.

It is probably not impossible to overcome these complications.... but it is very unlikely that I would work on this....

**Comment by wush978** [comment]
For the published date, we could try: 

```
pkg.dates <- local({
    .src <- readLines(url(sprintf("%s/../../web/packages/available_packages_by_date.html", contrib.urls["CRAN"])))
    .match <- regmatches(.src, regexec("<td> (\\d{4}-\\d{2}-\\d{2}) </td> <td> <a href=\"[^\"]+\">([^<]+)</a>", .src))
    .match <- Filter(f = function(x) length(x) > 0, .match)
    .retval <- as.Date(sapply(.match, "[", 2))
    names(.retval) <- sapply(.match, "[", 3)
    .retval
  })
```

For archive dates, we could try the `mtime` field from archives:

```
  archives <- lapply(contrib.urls, function(contrib.url) {
    tryCatch({
      con <- gzcon(url(sprintf("%s/Meta/archive.rds", contrib.url), "rb"))
      on.exit(close(con))
      readRDS(con)
    }, warning = function(e) list(), error = function(e) list())
  })

```

Finally, the `available.packages` could check the package version.

**Comment by wush978** [comment]
@gaborcsardi , I understand these problems. I think a database of metadata of MRAN is required.

Do you have any idea or suggestion about constructing such database?

I could construct the database by myself, but I like to hear any suggestion before doing it.

**Comment by gaborcsardi** [comment]
> I could construct the database by myself, but I like to hear any suggestion before doing it.

Well, my main suggestion is: *don't do it!* Sorry. I think it is way harder than you think. 

I think, that the value of the output is also questionable. If you want to use an older snapshot or R and CRAN, then just use MRAN directly, without `install_version`. If you want the current version of R, and an older version of one package, it is just better to rebuild it from source, in general.

Buy maybe I am just too pessimistic....

Anyway, if you do this, I don't think it is in the scope of `remotes`, so I'll close this issue.

**Comment by wush978** [comment]
@gaborcsardi ,

Thanks for your suggestion.
